# Configuración para Docker
spring.application.name=miGaleria

# Puerto del servidor
server.port=8080

# Configuración de la base de datos PostgreSQL en Docker
spring.datasource.url=jdbc:postgresql://db:5432/migaleria
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Configuración para producción
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=INFO
